version: '3'

services:
    db:
        image: mysql
        container_name: db
        ports:
            - ${MYSQL_PORT}:9001
        environment:
            MYSQL_DB: ${MYSQL_DB}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

    php:
        build:
            context: docker/php7-fpm
            args:
              PHP_PROJECT_FOLDER: symfonyyy

        container_name: php
        env_file: ./.env
        volumes:
            - ${PWD}:/var/www/<PROJECT_FOLDER>
        links:
            - db

    nginx:
        build:
            context: docker/nginx
            args:
              PROJECT_FOLDER: test
        container_name: nginx
        env_file: ./.env
        ports:
            - $WEB_PORT:80
        links:
            - php
        volumes:
            - ${PWD}:/var/www/<PROJECT_FOLDER>
            - ${LOGS_DIR}/nginx/:/var/log/nginx

#    elk:
#        container_name: nginx
#        image: willdurand/elk
#        env_file: ./.env
#        ports:
#            - ${ELK_PORT}:80
#        volumes:
#            - ./docker/elk/logstash:/etc/logstash
#            - ./docker/elk/logstash/patterns:/opt/logstash/patterns
#        volumes_from:
#            - php
#            - nginx

#    redis:
#        image: redis:3.2.10

#    node:
#        build: docker/node
#        env_file: ./.env
#        volumes:
#            - ${SYMFONY_APP_PATH}:/var/www/${PROJETCT_FOLDER}
#        command: bash -c "yarn && yarn dev"