#!/bin/bash

####################################################
# Commandline to initializ dockers container names #
####################################################

PROJECT_NAME='${PROJECT_FOLDER}'

FILES=$(find ./docker -type f)

sed -r -i -e  "s/<PROJECT_FOLDER>/$PROJECT_NAME/g" $FILES ./.env.dist ./.env ./docker-compose.yml
sed -r -i -e  "s/<PROJECT_FOLDER>/$PROJECT_NAME/g" ./bin/app
